name: Firebase Deploy
on:
  push:
    branches:
      - main-clean # Workflow only runs when pushing to the 'main' branch
jobs:
  build:
    runs-on: ubuntu-latest  # Uses the latest Ubuntu environment
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Checkout code from repository
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Using Node.js version 18
          
      - name: Install dependencies
        run: |
          npm install
          
      - name: Build the project
        run: |
          npm run build
          
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools
          
      - name: Deploy to Firebase Hosting
        run: |
          firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
