name: Firebase Deploy

on:
  push:
    branches:
      - main-clean

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '1//0gqbXKAXbMdlxCgYIARAAGBASNwF-L9IrjY9JwfUb2i_IxxXT8drkivxh0Z0-BlBkrHZJ-fh-K8L603g1kcSMdZdDY1L134XIEhA'
          channelId: live
          projectId: fir-react-devops
